apiVersion: v1
kind: Service
metadata:
  name: orchestrator-svc
  namespace: devops-tools
spec:
  selector:
    app: chatops-orchestrator
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
